version: "3"

networks:
  test:
   driver: bridge

name: universal-resolver

services:
  uni-resolver:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://uni-resolver:8080/1.0/testIdentifers || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
       uniresolver_web_driver_url_did_jwk:  http://host.docker.internal:8134
       uniresolver_web_driver_url_did_peer: http://host.docker.internal:8083
       uniresolver_web_driver_url_did_web:  http://host.docker.internal:8134
  uni-resolver-driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:4.3.0
    ports:
      - "8083:8081"
    networks: 
      - test
  did-jwk-driver:
    image: transmute/restricted-resolver:latest
    ports:
      - "8134:8080"
    networks: 
      - test
